#pragma once

#define LENGTH_OF_OWNER_ID 11
#define LENGTH_OF_OWNER_PASSWORD 8
#define LENGTH_OF_GROUP_ID 11
#define LENGTH_OF_INODE_ADDR 12
#define LENGTH_OF_FILE_MODE 10
#define LENGTH_OF_FILENAME 12
#define SIZE_OF_ONE_BLOCK 512
#define SIZE_OF_ALL_DATABLOCK 614400
#define SIZE_OF_ALL_BLOCK 621568
#define SIZE_OF_ONE_INODE 88
#define SIZE_OF_DIRECTORY 282
#define SIZE_OF_DIRECTORYNODE 14
#define SIZE_OF_USER 30
#define SUM_OF_INODE 60
#define SUM_OF_INODE_IN_ONE_BLOCK 5
#define SUM_OF_BLOCK 1214
#define SUM_OF_INODEBLOCK 12
#define SUM_OF_DATABLOCK 1200
#define SUM_OF_DATAGROUP 20
#define SUM_OF_DIRECTORY 60
#define SUM_OF_GROUPLINK 60
#define SUM_OF_DIRECTORY_IN_ONE_DIR 10
#define NUMBER_OF_THE_START_OF_THE_HOMEBLOCK 0
#define NUMBER_OF_THE_START_OF_THE_SUPERBLOCK 1
#define NUMBER_OF_THE_START_OF_THE_INODEBLOCK 2
#define NUMBER_OF_THE_START_OF_THE_DATABLOCK 14

